# Generated by Django 6.0.6 on 2026-06-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('time_known', models.BooleanField(default=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('tz_name', models.CharField(max_length=64)),
                ('datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_system', models.CharField(default='Placidus', max_length=20)),
                ('zodiac', models.CharField(default='Tropical', max_length=20)),
                ('data', models.JSONField()),
                ('svg', models.TextField(blank=True, null=True)),
                ('engine_version', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='api.birthdata')),
            ],
        ),
    ]
