# Generated by Django 6.0.6 on 2026-06-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geonameid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asciiname', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country_code', models.CharField(max_length=2)),
                ('admin1_code', models.CharField(blank=True, max_length=20)),
                ('admin1', models.CharField(blank=True, max_length=200)),
                ('tz_geonames', models.CharField(blank=True, max_length=64)),
                ('population', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GeoNameToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('geoname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.geoname')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='api_geoname_token_92df43_idx'), models.Index(fields=['token'], name='geoname_token_prefix', opclasses=['varchar_pattern_ops'])],
            },
        ),
    ]
