# Generated by Django 6.0.6 on 2026-06-30 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
