# Generated by Django 6.0.6 on 2026-06-30 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chart_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpretations', to='api.installation'),
        ),
    ]
