# Generated by Django 6.0.6 on 2026-06-30 18:34

from django.conf import settings
from django.db import migrations, models


def _regalo_de_bienvenida():
    """El default del campo `free_balance`, que la 0025 borró.

    Vivía en `api.models` y esta migración lo nombraba por ruta de import.
    Se mudó acá cuando el campo dejó de existir: una migración congela el
    código del día que se escribió, y no puede depender de una función que
    el modelo ya no necesita.
    """
    return settings.INSTALL_FREE_CREDITS


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_interpretation_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('free_balance', models.PositiveIntegerField(default=_regalo_de_bienvenida)),
                ('paid_balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
