# Generated by Django 6.0.6 on 2026-06-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('apple', 'apple'), ('google', 'google')], max_length=10)),
                ('sub', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='api.account')),
            ],
            options={
                'unique_together': {('provider', 'sub')},
            },
        ),
    ]
