# Generated by Django 6.0.6 on 2026-06-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('free_credits_consumed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
