# Generated by Django 6.0.6 on 2026-06-30 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subtombstone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='api.account'),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpretations', to='api.account'),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('free_grant', 'free_grant'), ('purchase', 'purchase'), ('consumption', 'consumption'), ('refund', 'refund'), ('adjustment', 'adjustment')], max_length=20)),
                ('lot', models.CharField(choices=[('free', 'free'), ('paid', 'paid')], max_length=4)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_txns', to='api.account')),
                ('interpretation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_txns', to='api.interpretation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
