# Generated by Django 6.0.6 on 2026-06-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretation',
            name='installation',
        ),
        migrations.DeleteModel(
            name='Installation',
        ),
    ]
