# Generated by Django 6.0.6 on 2026-07-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_interpretation_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='refund_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='paid_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='uniq_credit_txn_external_id'),
        ),
    ]
