# Generated by Django 6.0.6 on 2026-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_account_flagged_account_refund_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='content_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
