# Generated by Django 6.0.6 on 2026-07-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_backfill_content_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdata',
            name='place_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
