# Generated by Django 6.0.6 on 2026-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_birthdata_place_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideridentity',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
