# Generated by Django 6.0.6 on 2026-08-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_provideridentity_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='completa',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InterpretationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('orden', models.PositiveSmallIntegerField()),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interpretation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='api.interpretation')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('interpretation', 'slug')},
            },
        ),
    ]
