# Generated by Django 6.0.6 on 2026-08-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_backfill_completa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interpretation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='tier',
            field=models.CharField(choices=[('corto', 'corto'), ('largo', 'largo')], default='largo', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='interpretation',
            unique_together={('chart', 'lang', 'prompt_version', 'tier')},
        ),
    ]
