# Generated by Django 6.0.6 on 2026-08-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_interpretation_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='intentos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
