# Generated by Django 6.0.6 on 2026-08-31 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_interpretation_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deuda',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Derecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=40)),
                ('cantidad_restante', models.PositiveIntegerField(blank=True, null=True)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derechos', to='api.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'codigo_producto'), name='uniq_derecho_cuenta_producto'), models.CheckConstraint(condition=models.Q(models.Q(('cantidad_restante__isnull', False), ('vigente_hasta__isnull', True)), models.Q(('cantidad_restante__isnull', True), ('vigente_hasta__isnull', False)), _connector='OR'), name='derecho_es_consumible_o_acceso')],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('otorgamiento', 'otorgamiento'), ('consumo', 'consumo'), ('devolucion', 'devolucion'), ('revocacion', 'revocacion')], max_length=12)),
                ('origen', models.CharField(choices=[('compra', 'compra'), ('regalo', 'regalo'), ('cupon', 'cupon'), ('ajuste', 'ajuste')], max_length=8)),
                ('cantidad', models.IntegerField(help_text='firmado: + ingresa, - consume')),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='api.account')),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='api.chart')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='uniq_movimiento_external_id')],
            },
        ),
    ]
