# Generated by Django 6.0.6 on 2026-09-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_borrar_saldos_viejos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(max_length=100, unique=True)),
                ('codigo_producto', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_polar', to='api.account')),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_polar', to='api.chart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
