# Generated by Django 6.0.6 on 2026-09-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_polar_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='polarcheckout',
            name='locale',
            field=models.CharField(default='es', max_length=5),
        ),
    ]
