# Generated by Django 6.0.6 on 2026-09-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_polarcheckout_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='polarcheckout',
            name='acreditado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
