# Generated by Django 6.0.6 on 2026-09-07 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_pasarelacheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasarelacheckout',
            name='descuento_centavos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{3,40}$', 'Sólo A-Z, 0-9 y guión, de 3 a 40')])),
                ('descripcion', models.CharField(blank=True, help_text='Para qué es. Uso interno.', max_length=200)),
                ('porcentaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('productos', models.JSONField(default=list, help_text='Códigos del catálogo que abarca.')),
                ('usos_maximos', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('vence_el', models.DateField(blank=True, help_text='Vence a las 23:59:59 de ese día, hora de Buenos Aires.', null=True)),
                ('stripe_coupon_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_promotion_code_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('porcentaje__gte', 1), ('porcentaje__lte', 100)), name='cupon_porcentaje_1_a_100')],
            },
        ),
        migrations.AddField(
            model_name='pasarelacheckout',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='api.cupon'),
        ),
        migrations.CreateModel(
            name='CuponUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=40)),
                ('descuento_centavos', models.PositiveIntegerField()),
                ('monto_pagado_centavos', models.PositiveIntegerField()),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('revocado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_cupon', to='api.account')),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_cupon', to='api.pasarelacheckout')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='api.cupon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
