# Generated by Django 6.0.6 on 2026-09-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasarelacheckout',
            name='reembolsado_centavos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
