# Generated by Django 6.0.6 on 2026-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_pasarelacheckout_reembolsado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasarelacheckout',
            name='url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='pasarelacheckout',
            name='vencido_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
