# Generated by Django 6.0.6 on 2026-09-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_pasarelacheckout_url_vencido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideridentity',
            name='provider',
            field=models.CharField(choices=[('apple', 'apple'), ('google', 'google'), ('email', 'email')], max_length=10),
        ),
        migrations.CreateModel(
            name='CodigoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('destino', models.CharField(blank=True, default='', max_length=200)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'creado_en'], name='api_codigoa_email_c2478c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('usado_en__isnull', True)), fields=('email',), name='un_codigo_vigente_o_expirado_sin_usar_por_direccion')],
            },
        ),
    ]
