# Generated by Django 6.0.6 on 2026-09-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_provideridentity_provider_codigoacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoacceso',
            name='envios',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
