# Generated by Django 6.0.6 on 2026-09-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_normalizar_casing_de_cuentas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='codigoacceso',
            name='un_codigo_vigente_o_expirado_sin_usar_por_direccion',
        ),
    ]
