# Generated by Django 6.0.6 on 2026-10-06 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_checkout_precio_congelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('producto', models.CharField(choices=[('natal', 'natal'), ('vinculo', 'vinculo')], max_length=20)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('engine_version', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujetos', to='api.account')),
                ('natal_de', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujeto_natal', to='api.chart')),
            ],
        ),
        migrations.AddField(
            model_name='interpretation',
            name='sujeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='api.sujeto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='sujeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='api.sujeto'),
        ),
        migrations.AddField(
            model_name='pasarelacheckout',
            name='sujeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='api.sujeto'),
        ),
        migrations.AddConstraint(
            model_name='interpretation',
            constraint=models.UniqueConstraint(fields=('sujeto', 'lang', 'prompt_version', 'tier'), name='uniq_interpretacion_por_sujeto'),
        ),
        migrations.AddConstraint(
            model_name='sujeto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('natal_de__isnull', False), ('producto', 'natal')), models.Q(models.Q(('producto', 'natal'), _negated=True), ('natal_de__isnull', True)), _connector='OR'), name='sujeto_natal_tiene_carta_y_solo_el'),
        ),
    ]
