# Generated by Django 6.0.6 on 2026-10-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rellenar_sujetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasarelacheckout',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasarelacheckout',
            name='canjeado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasarelacheckout',
            name='cuenta_nueva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasarelacheckout',
            name='nonce_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
