# Generated by Django 6.0.6 on 2026-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_pasarela_anonima'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasarelacheckout',
            name='saldo_deuda',
            field=models.BooleanField(default=False),
        ),
    ]
