# Generated by Django 6.0.6 on 2026-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_pasarela_saldo_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdata',
            name='trato',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='trato',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
