# Generated by Django 6.0.6 on 2026-10-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_trato_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='traducido_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traducciones', to='api.interpretation'),
        ),
    ]
