# Generated by Django 6.0.6 on 2026-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_traducido_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ambito', models.CharField(choices=[('anonimo', 'anonimo'), ('cuenta', 'cuenta')], max_length=10)),
                ('usados', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fecha', 'ambito'), name='uniq_cupo_por_dia_y_ambito')],
            },
        ),
    ]
