# Generated by Django 6.0.6 on 2026-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_cupodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='avisada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
