# Generated by Django 6.0.6 on 2026-10-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_interpretation_avisada_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaCache',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'django_cache',
                'managed': False,
            },
        ),
    ]
