# Generated by Django 6.0.6 on 2026-10-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_borrar_columnas_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='en_lista',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.CreateModel(
            name='SujetoCarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('rol', models.CharField(blank=True, default='', max_length=20)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_sujetos', to='api.chart')),
                ('sujeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='api.sujeto')),
            ],
            options={
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('sujeto', 'orden'), name='sujeto_carta_orden_unico')],
            },
        ),
    ]
