"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import sys


import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

from config.observabilidad import init_sentry


def _mapa_json(nombre: str) -> dict:
    """Un mapeo `{clave: valor}` que llega por variable de entorno.

    Con `json.loads` a secas, una variable mal escrita —comillas de más al
    pegarla en el panel de deploy, una coma suelta— levanta al IMPORTAR este
    módulo, así que Django no arranca y se cae el sitio entero por un error en
    una variable del cobro. Acá se degrada a un mapeo vacío y se avisa por
    stderr, que es donde se lee el log del contenedor.

    Lo que queda roto es sólo lo que depende del mapeo, y ruidosamente: el
    checkout responde 503 y el webhook descarta con "precio que no mapeamos".
    Eso se arregla corrigiendo la variable; una API caída, no.
    """
    crudo = os.environ.get(nombre, "").strip()
    if not crudo:
        return {}
    try:
        valor = json.loads(crudo)
    except ValueError as exc:
        print(f"[settings] {nombre} no es JSON válido ({exc}): se ignora", file=sys.stderr)
        return {}
    if not isinstance(valor, dict):
        print(f"[settings] {nombre} no es un mapeo JSON: se ignora", file=sys.stderr)
        return {}
    return valor

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# DEBUG=1 para desarrollo; en prod se deja sin setear (False).
DEBUG = os.environ.get("DEBUG", "0") == "1"

# SECRET_KEY desde env en prod. El fallback inseguro SOLO existe con DEBUG=1;
# sin DEBUG y sin SECRET_KEY, fail-fast (no arrancar con una key conocida).
SECRET_KEY = os.environ.get("SECRET_KEY") or (
    "django-insecure-$-4_@!44ff*g(ppt70mbj9czrqiy^7i4w$@3m29yr_!%yvf$cp" if DEBUG else ""
)
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY env var es obligatoria cuando DEBUG está apagado")

# Lista separada por comas, p.ej. "api.midominio.com,carta-astral.midominio.com".
# El healthcheck de Docker corre dentro del contenedor y pregunta por
# `localhost`, no por el dominio público. Django valida el `Host` en el
# middleware, antes de cualquier vista: sin estos dos, `/healthz/` devolvía 400
# y Coolify daba la aplicación por muerta —comprobado contra producción el
# 13-08-2026, donde el dominio público respondía 200 y el pedido interno 400—.
# No aflojan nada: Traefik enruta por dominio, así que un pedido con
# `Host: localhost` sólo puede venir de adentro de la red de Docker.
INTERNAL_HOSTS = ["localhost", "127.0.0.1"]

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
if ALLOWED_HOSTS:
    ALLOWED_HOSTS += INTERNAL_HOSTS
if DEBUG and not ALLOWED_HOSTS:
    # En desarrollo el teléfono y la web de la app le pegan por la IP LAN de
    # la Mac (cambia por DHCP); cualquier host es aceptable con DEBUG.
    ALLOWED_HOSTS = ["*"]

# Necesario para el admin (POST de login) sobre HTTPS detrás del proxy de Coolify.
# Lista separada por comas con esquema, p.ej. "https://api.midominio.com".
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Coolify/Traefik terminan TLS y reenvían con X-Forwarded-Proto. Sin esto, Django
# cree que toda request es http y rompe redirects/cookies seguras detrás del proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Hardening sólo en prod (DEBUG off). El redirect HTTP->HTTPS lo hace Coolify/Traefik,
# NO Django (SECURE_SSL_REDIRECT), porque el healthcheck interno pega por HTTP sin el
# header X-Forwarded-Proto y un redirect lo haría fallar.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # conservador: no fuerza HSTS en otros subdominios


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # `wagtail.search` (abajo) define su tabla de índice con `SearchVectorField`
    # y `GinIndex` cuando la base es Postgres (lo decide `modelsearch` mirando
    # `connection.vendor` al importarse). Sin este app, Django no falla al
    # correr sobre SQLite (donde no aplica) pero SÍ falla el `migrate`/
    # `makemigrations` real en producción (Postgres) con
    # `postgres.E005: 'django.contrib.postgres' must be in INSTALLED_APPS`.
    # Verificado en Tarea 9 corriendo el arranque contra Postgres de verdad;
    # el desarrollo local usa SQLite por default y nunca lo disparó.
    "django.contrib.postgres",
    "rest_framework",
    "api",
    # --- CMS de las notas. ---
    # `wagtail.documents` va instalado: sin él, el admin ni siquiera arranca
    # (`wagtailadmin_tags.wagtail_config` reversea su API incondicionalmente,
    # y sin el módulo esa ruta no existe -> 500 en cualquier página del panel,
    # login incluido). Que esté instalado NO significa que se pueda subir nada:
    # `WAGTAILDOCS_EXTENSIONS` (más abajo) bloquea toda subida de documentos,
    # que era XSS almacenado sobre el origen del admin. La lista blanca de
    # extensiones de imagen (Tarea 7) es aparte y también sigue en pie.
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.images",
    "wagtail.documents",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail.api.v2",
    "modelcluster",
    "taggit",
    "axes",
    "cms",
]

# `manage.py check` sale limpio o no sirve para nada: cuatro warnings fijos que
# nadie puede accionar entrenan a ignorar la salida, y el quinto —el que sí
# importa— pasa desapercibido.
#
# treebeard.E001 avisa que el manager por defecto de un MP_Node no subclasea
# `MP_NodeManager` y que eso será un error en Treebeard 6. Los cuatro que
# aparecen acá son de Wagtail, no nuestros: `BasePageManager(models.Manager)`
# (wagtail/models/pages.py:142) y el equivalente de Collection. Nuestros dos
# modelos del CMS lo heredan por ser subclases de `Page` — no hay manager
# propio que corregir, y pisar el de Wagtail sería peor que el warning.
# Verificado contra wagtail 7.4.2 / treebeard 5.3.0, las instaladas.
#
# `tests/api/test_system_checks.py` falla el día que Wagtail lo arregle, para
# que este silencio no sobreviva a su motivo.
SILENCED_SYSTEM_CHECKS = ["treebeard.E001"]

WAGTAIL_SITE_NAME = "ASTRA"
# Wagtail lo exige para armar URLs absolutas en el admin, y la API del CMS la
# usa para armar `full_url` en las imágenes (contrato con la web: usa esa
# clave, no `url`, para las portadas). Mismo patrón que `SECRET_KEY`: default
# a localhost SÓLO en DEBUG; sin la env var en producción, fail-fast en vez de
# arrancar con un default que deja las portadas de todas las notas rotas en
# la web, sin ningún error visible.
WAGTAILADMIN_BASE_URL = os.environ.get("WAGTAILADMIN_BASE_URL") or (
    "http://localhost:8000" if DEBUG else ""
)
if not WAGTAILADMIN_BASE_URL:
    raise ImproperlyConfigured(
        "WAGTAILADMIN_BASE_URL env var es obligatoria cuando DEBUG está apagado: "
        "sin ella, `full_url` en la API de imágenes apunta a localhost y las "
        "portadas de las notas salen rotas en la web."
    )

# El `detail_url` que la API pone en cada página. Sin esto lo arma con el
# `Site` de Wagtail, que apunta al dominio de la web —donde esta API no
# existe—, así que el campo salía con una URL que devuelve 404. Es el mismo
# origen que el admin porque la API vive en este backend, no en la web.
WAGTAILAPI_BASE_URL = WAGTAILADMIN_BASE_URL

# Dominio público de la web (Next.js), NO del backend. Este backend es
# headless: `config/urls.py` nunca monta `wagtail.urls`, así que Wagtail no
# tiene ninguna URL propia para una página del CMS. Los enlaces internos del
# cuerpo de una nota (`cms/wagtail_hooks.py`, `NotaLinkHandler`) se resuelven
# contra esta variable, con el esquema de rutas `/notas` que ya define el
# plan del frontend (docs/2026-07-31-spec-cms-wagtail.md). Mismo patrón que
# `WAGTAILADMIN_BASE_URL`: default sólo en DEBUG (puerto de `next dev`),
# fail-fast en producción en vez de publicar enlaces a localhost.
WEB_BASE_URL = os.environ.get("WEB_BASE_URL") or ("http://localhost:3000" if DEBUG else "")
if not WEB_BASE_URL:
    raise ImproperlyConfigured(
        "WEB_BASE_URL env var es obligatoria cuando DEBUG está apagado: sin ella, "
        "los enlaces internos del cuerpo de una nota resolverían contra localhost."
    )

# --- Avisos por mail (Resend) ---
# Sin la key, `notificaciones` deja el aviso en el log y no intenta mandarlo:
# eso es lo que corre en desarrollo y en los tests. En producción, sin esto,
# quien paga y cierra la pestaña no se entera nunca de que su informe está listo.
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
# La misma dirección que el sitio publica en el pie y en los legales
# (`LEGAL_CONTACT`): un aviso de compra que llega desde otra dirección se lee
# como si fuera de otro.
#
# Enviar desde la raíz NO obliga a tocar el SPF: un registro SPF admite varios
# `include:` y el de ImprovMX sigue igual (lo que no se puede es tener DOS
# registros SPF). Lo que sí hay que dejar afuera es el MX que Resend ofrece
# para la raíz: viene con prioridad 9 contra el 10 de ImprovMX, así que
# cargarlo desviaría todo el correo ENTRANTE. Sin ese MX se envía igual; sólo
# se pierde la recepción por Resend, que no usamos.
MAIL_FROM = os.environ.get("MAIL_FROM", "ASTRA <info@astraguia.com>")

# --- Medición de negocio (PostHog) ---
# Sólo lo que el navegador no puede medir: que la plata haya entrado. Sin la
# key no sale nada, que es lo que corre en desarrollo y en los tests. Es la
# misma cuenta de PostHog que usa la web; el proyecto distingue el origen por
# `$lib`.
# De dónde viene cada evento. El staging local es un espejo de producción
# —mismas credenciales, salvo Stripe, que va en modo test—, así que sin esta
# marca una compra de prueba con la tarjeta 4242 entraría al mismo embudo que
# las de verdad e inflaría la tasa de conversión, que es el número del que
# depende decidir sobre tráfico pago. El default es "produccion" a propósito:
# olvidarse de declararla en el servidor no puede hacer desaparecer ventas
# reales del embudo.
ENTORNO = os.environ.get("ENTORNO", "produccion")
POSTHOG_KEY = os.environ.get("POSTHOG_KEY", "")
POSTHOG_HOST = os.environ.get("POSTHOG_HOST", "https://us.i.posthog.com")

# Un formulario de login expuesto a internet sin límite de intentos no es una
# hipótesis de riesgo: es un problema conocido.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # horas
AXES_LOCKOUT_PARAMETERS = ["ip_address"]
# Sin esto, la IP que axes bloquea es la de Traefik para TODAS las requests, o
# sea que el bloqueo cae sobre todo el mundo a la vez: ver `config/axes_ip.py`.
AXES_CLIENT_IP_CALLABLE = "config.axes_ip.ip_del_cliente"
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # `LANGUAGE_CODE` es global y lo pide el CMS en 'es' (ver más abajo), pero
    # el que decide el idioma de una respuesta de `/api/` es el cliente: sin
    # este middleware, el `detail` de un 429 o un 401 sale en español para la
    # app en inglés y en portugués. Va después de Session y antes de Common,
    # como pide la documentación de Django.
    'django.middleware.locale.LocaleMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

if DEBUG:
    # CORS abierto SOLO en desarrollo, para la build web local de la app.
    MIDDLEWARE.insert(0, 'config.middleware.DevCorsMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
    )
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_AUTHENTICATION_CLASSES": ["api.auth.AccountTokenAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["api.permissions.HasAccount"],
    "DEFAULT_THROTTLE_RATES": {
        "interpretation": os.environ.get("INTERPRETATION_RATE", "20/day"),
        "install": os.environ.get("INSTALL_RATE", "30/day"),
        "auth": os.environ.get("AUTH_RATE", "30/day"),
        "chart": os.environ.get("CHART_RATE", "60/day"),
        # Sin cuenta el techo cae sobre la IP, que comparten todos los que
        # salen por un mismo NAT: generoso a propósito, porque lo que
        # frena es el abuso automatizado, no una oficina entera.
        "preview": os.environ.get("PREVIEW_RATE", "60/hour"),
        "geocode": os.environ.get("GEOCODE_RATE", "240/hour"),
        # El PDF no cobra créditos, pero cada uno son ~300 ms de CPU en un worker
        # sincrónico de los tres: sin techo, un bucle de fetch deja el sitio sin
        # workers. Generoso a propósito: bajarse las cartas propias es legítimo.
        "pdf": os.environ.get("PDF_RATE", "120/day"),
        # Público y cacheado: el techo es contra el abuso, no contra el uso.
        "sky": os.environ.get("SKY_RATE", "240/hour"),
    },
}

# --- api-interpret (control de costo) ---
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
# Tope global diario de generaciones NUEVAS (cache miss). Las cacheadas no cuentan.
# Un informe completo cuesta ~US$0,45 (ocho llamadas con contexto acumulado),
# no los ~US$0,03 de la lectura vieja. Con el cap anterior de 500 el techo de
# gasto diario en informes regalados pasaba de US$15 a más de US$200.
INTERPRETATION_DAILY_CAP = int(os.environ.get("INTERPRETATION_DAILY_CAP", "40"))
# Free-tier: informes gratis por cuenta; después, modo pago (IAP, frente con la app).
# Tres, no uno: el resumen gratis existe para que alguien se lo muestre a otra
# persona, y con uno solo el dueño de la cuenta ya lo gastó en su propia carta.
INSTALL_FREE_CREDITS = int(os.environ.get("INSTALL_FREE_CREDITS", "3"))

# --- SSO / cuentas ---
APPLE_AUD = os.environ.get("APPLE_AUD", "")  # bundle id de la app iOS; vacío => auth Apple 503 (fail-closed)
GOOGLE_AUD = os.environ.get("GOOGLE_AUD", "")  # OAuth client id; vacío => auth Google 503
APPLE_ISS = os.environ.get("APPLE_ISS", "https://appleid.apple.com")
GOOGLE_ISS = os.environ.get("GOOGLE_ISS", "https://accounts.google.com")
APPLE_JWKS_URL = os.environ.get("APPLE_JWKS_URL", "https://appleid.apple.com/auth/keys")
GOOGLE_JWKS_URL = os.environ.get("GOOGLE_JWKS_URL", "https://www.googleapis.com/oauth2/v3/certs")
JWKS_TTL_SECONDS = int(os.environ.get("JWKS_TTL_SECONDS", str(12 * 3600)))
SESSION_TTL_DAYS = int(os.environ.get("SESSION_TTL_DAYS", "90"))

# Credenciales del Apple ID server API (canje de authorization_code + revoke del
# borrado de cuenta, guideline 5.1.1(v)). Fail-OPEN a propósito: sin ellas el
# login y el borrado siguen andando, sólo se saltea el revoke (con log de error).
APPLE_TEAM_ID = os.environ.get("APPLE_TEAM_ID", "")  # Apple Developer → Membership
APPLE_KEY_ID = os.environ.get("APPLE_KEY_ID", "")  # Key ID de la key "Sign in with Apple"
APPLE_PRIVATE_KEY = os.environ.get("APPLE_PRIVATE_KEY", "")  # contenido PEM del .p8

# --- IAP / RevenueCat ---
# Header Authorization que RevenueCat manda en cada webhook (Dashboard → Webhooks).
REVENUECAT_WEBHOOK_AUTH = os.environ.get("REVENUECAT_WEBHOOK_AUTH", "")
# Mapa product_id (App Store / Play) → créditos que otorga. JSON en env.
REVENUECAT_PRODUCT_CREDITS = _mapa_json("REVENUECAT_PRODUCT_CREDITS")

# --- Polar (cobro en la web) -------------------------------------------------
# El sandbox es OTRA organización: cuenta, productos y token propios. El default
# es producción a propósito — un valor mal escrito no puede mandar los pagos
# reales al sandbox, que no cobra.
# Stripe es la pasarela: cobra como merchant of record (Managed Payments), se
# ocupa del IVA en más de 80 países y avisa por webhook.
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
# `price_id → código del catálogo`, en la dirección en que lo consulta el
# webhook. Los ids de Stripe no se comparten entre modo test y live, así que
# este mapeo es distinto en cada entorno y el código, el mismo.
STRIPE_PRECIOS = _mapa_json("STRIPE_PRECIOS")
# Plantilla con `{locale}` (lo pone el checkout, de la lista blanca) y con
# `{CHECKOUT_SESSION_ID}`, que reemplaza Stripe al redirigir.
STRIPE_SUCCESS_URL = os.environ.get("STRIPE_SUCCESS_URL", "")
# Cantidad de reembolsos que marca una cuenta como abuso.
REFUND_FLAG_THRESHOLD = int(os.environ.get("REFUND_FLAG_THRESHOLD", "3"))

# --- Superficie de la app móvil ---
# La app no se retoma por ahora: lo que se termina es la web. Nada de esto se
# borra, se apaga. El fail-closed de más arriba (401 sin REVENUECAT_WEBHOOK_AUTH,
# 503 sin APPLE_AUD) sigue siendo la defensa real; estos flags son la decisión
# escrita, para que el endpoint no quede expuesto por olvido de una credencial.
# Dos flags y no uno: lo más probable es que la app vuelva por una plataforma
# antes que por la otra, y un booleano único obligaría a partirlo entonces.
APP_AUTH_ENABLED = os.environ.get("APP_AUTH_ENABLED", "0") == "1"
IAP_WEBHOOK_ENABLED = os.environ.get("IAP_WEBHOOK_ENABLED", "0") == "1"

# Cache compartido entre workers: el throttle, el tope global y el lock viven
# acá. En prod (multi-worker) DEBE ser compartido y persistente -> DatabaseCache
# (USE_DB_CACHE=1 + `manage.py createcachetable`). LocMem en prod NO limita:
# cada worker tiene su propio contador y los muros de costo no funcionan.
if os.environ.get("USE_DB_CACHE"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_cache",
        }
    }
elif not DEBUG:
    # Fail-fast, no degradación silenciosa: con LocMem cada worker de gunicorn
    # tiene SU PROPIO contador, así que el tope global de gasto, el throttle y
    # el lock de interpretación dejan de limitar sin que nada avise. Es un
    # agujero de costo, y prefiere no arrancar antes que arrancar sin muros.
    raise ImproperlyConfigured(
        "En producción hace falta caché compartida: seteá USE_DB_CACHE=1 "
        "(y corré `manage.py createcachetable`). Con LocMem el cap de costo, "
        "el throttle y el lock de interpretación no limitan nada."
    )
else:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# El contenido del CMS vive en los mismos tres idiomas que la app y la web, y
# éste es el que Wagtail toma como locale por defecto (`Locale.get_default()`).
# OJO: el setting es global, no sólo del CMS — es el idioma de fallback de toda
# respuesta traducible, incluidos los errores de DRF en `/api/`. Que cada
# cliente reciba el suyo lo resuelve `LocaleMiddleware` (ver MIDDLEWARE).
LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

WAGTAIL_I18N_ENABLED = True
WAGTAIL_CONTENT_LANGUAGES = [("es", "Español"), ("en", "English"), ("pt", "Português")]

# El default de Wagtail es 20, y a la nota 21 el listado y el sitemap de la web
# habrían empezado a omitir notas sin que nada fallara. La API es pública pero
# sólo devuelve notas publicadas, así que el techo no protege nada sensible: es
# el costo de una respuesta grande. Cuando el blog pase de 200 notas hay que
# paginar de verdad, no volver a subir este número.
WAGTAILAPI_LIMIT_MAX = 200


# Sólo mapas de bits: un SVG es un documento con scripts (RF6).
WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp"]

# `wagtail.documents` va instalado (ver INSTALLED_APPS más arriba: sin él el
# admin no arranca), pero el CMS es para notas de blog —texto e imágenes— y
# no hay ningún caso de uso de documentos. Un `.html` o un `.svg` subidos por
# ese formulario se sirven desde `/media/documents/...`, el mismo origen
# donde vive la sesión del admin: XSS almacenado (verificado, revisión final).
#
# `AbstractDocument.clean()` sólo valida contra `WAGTAILDOCS_EXTENSIONS`
# cuando la lista es truthy (`if allowed_extensions:`): una lista VACÍA no
# activa ninguna validación y dejaría pasar cualquier archivo. Por eso la
# lista lleva una extensión que ningún archivo real puede tener: bloquea
# absolutamente todo, sin el agujero de la lista vacía.
WAGTAILDOCS_EXTENSIONS = ["__ningun-documento-tiene-esta-extension__"]

# La web regenera la nota cuando el CMS avisa. Sin estas dos, no se avisa.
REVALIDATE_URL = os.environ.get("REVALIDATE_URL", "")
REVALIDATE_SECRET = os.environ.get("REVALIDATE_SECRET", "")

# Media (imágenes subidas al CMS)
# https://docs.djangoproject.com/en/6.0/topics/files/

# Fuera de /app, porque el Dockerfile reemplaza ese directorio entero en cada
# deploy (`COPY --from=builder /app /app`). En Coolify este directorio se
# monta como volumen persistente: ver Dockerfile.
#
# En desarrollo `/data/media` no existe y es la raíz del disco: subir una
# portada desde el panel moría con PermissionError al intentar crearlo. Mismo
# patrón que el resto del archivo: default de desarrollo sólo con DEBUG.
MEDIA_ROOT = os.environ.get("MEDIA_ROOT") or (
    str(BASE_DIR / "media") if DEBUG else "/data/media"
)
MEDIA_URL = "/media/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise sirve el static del admin sin necesidad de Nginx/CDN. Manifest +
# compresión: requiere `collectstatic` (se corre en el build de la imagen).
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Logging: a stdout, que es donde `docker logs` (y Coolify) lo pueden leer.
#
# Sin esto, `api` e `interpret` propagaban a un root sin handlers y sólo salía
# lo de nivel ERROR, por el handler de último recurso de la stdlib. El código
# del informe dice en tres lugares que "nunca deja una excepción sin loguear"
# — y era mentira por omisión. El 01-09-2026 un informe pago se cortó en la
# sección 3 y no quedó una sola línea sobre por qué.
#
# INFO para los dos módulos propios, no WARNING: `interpret.generator` loguea
# en INFO el `stop_reason` y los `output_tokens` de cada llamada al modelo, que
# es el dato con el que se decide si el techo de tokens quedó corto (ya pasó
# con la lectura breve). WARNING para el resto, para no ahogar eso en el ruido
# de Django.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "consola": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "consola",
        },
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        "api": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "interpret": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}

# Sentry: opcional (sin DSN no se inicializa). Ver `config/observabilidad.py`.
SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
init_sentry(
    dsn=SENTRY_DSN,
    entorno=os.environ.get("SENTRY_ENVIRONMENT") or ("desarrollo" if DEBUG else "produccion"),
    release=os.environ.get("SENTRY_RELEASE") or None,
)
