"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# DEBUG=1 para desarrollo; en prod se deja sin setear (False).
DEBUG = os.environ.get("DEBUG", "0") == "1"

# SECRET_KEY desde env en prod. El fallback inseguro SOLO existe con DEBUG=1;
# sin DEBUG y sin SECRET_KEY, fail-fast (no arrancar con una key conocida).
SECRET_KEY = os.environ.get("SECRET_KEY") or (
    "django-insecure-$-4_@!44ff*g(ppt70mbj9czrqiy^7i4w$@3m29yr_!%yvf$cp" if DEBUG else ""
)
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY env var es obligatoria cuando DEBUG está apagado")

# Lista separada por comas, p.ej. "api.midominio.com,carta-astral.midominio.com".
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    # En desarrollo el teléfono y la web de la app le pegan por la IP LAN de
    # la Mac (cambia por DHCP); cualquier host es aceptable con DEBUG.
    ALLOWED_HOSTS = ["*"]

# Necesario para el admin (POST de login) sobre HTTPS detrás del proxy de Coolify.
# Lista separada por comas con esquema, p.ej. "https://api.midominio.com".
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Coolify/Traefik terminan TLS y reenvían con X-Forwarded-Proto. Sin esto, Django
# cree que toda request es http y rompe redirects/cookies seguras detrás del proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Hardening sólo en prod (DEBUG off). El redirect HTTP->HTTPS lo hace Coolify/Traefik,
# NO Django (SECURE_SSL_REDIRECT), porque el healthcheck interno pega por HTTP sin el
# header X-Forwarded-Proto y un redirect lo haría fallar.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # conservador: no fuerza HSTS en otros subdominios


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "api",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # CORS abierto SOLO en desarrollo, para la build web local de la app.
    MIDDLEWARE.insert(0, 'config.middleware.DevCorsMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
    )
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_AUTHENTICATION_CLASSES": ["api.auth.AccountTokenAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["api.permissions.HasAccount"],
    "DEFAULT_THROTTLE_RATES": {
        "interpretation": os.environ.get("INTERPRETATION_RATE", "20/day"),
        "install": os.environ.get("INSTALL_RATE", "30/day"),
        "auth": os.environ.get("AUTH_RATE", "30/day"),
        "chart": os.environ.get("CHART_RATE", "60/day"),
    },
}

# --- api-interpret (control de costo) ---
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
# Tope global diario de generaciones NUEVAS (cache miss). Las cacheadas no cuentan.
INTERPRETATION_DAILY_CAP = int(os.environ.get("INTERPRETATION_DAILY_CAP", "500"))
# Free-tier: 1 carta gratis por instalación; después, modo pago (IAP, frente con la app).
INSTALL_FREE_CREDITS = int(os.environ.get("INSTALL_FREE_CREDITS", "1"))

# --- SSO / cuentas ---
APPLE_AUD = os.environ.get("APPLE_AUD", "")  # bundle id de la app iOS; vacío => auth Apple 503 (fail-closed)
GOOGLE_AUD = os.environ.get("GOOGLE_AUD", "")  # OAuth client id; vacío => auth Google 503
APPLE_ISS = os.environ.get("APPLE_ISS", "https://appleid.apple.com")
GOOGLE_ISS = os.environ.get("GOOGLE_ISS", "https://accounts.google.com")
APPLE_JWKS_URL = os.environ.get("APPLE_JWKS_URL", "https://appleid.apple.com/auth/keys")
GOOGLE_JWKS_URL = os.environ.get("GOOGLE_JWKS_URL", "https://www.googleapis.com/oauth2/v3/certs")
JWKS_TTL_SECONDS = int(os.environ.get("JWKS_TTL_SECONDS", str(12 * 3600)))
SESSION_TTL_DAYS = int(os.environ.get("SESSION_TTL_DAYS", "90"))

# --- IAP / RevenueCat ---
# Header Authorization que RevenueCat manda en cada webhook (Dashboard → Webhooks).
REVENUECAT_WEBHOOK_AUTH = os.environ.get("REVENUECAT_WEBHOOK_AUTH", "")
# Mapa product_id (App Store / Play) → créditos que otorga. JSON en env.
REVENUECAT_PRODUCT_CREDITS = json.loads(os.environ.get("REVENUECAT_PRODUCT_CREDITS", "{}"))
# Cantidad de reembolsos que marca una cuenta como abuso.
REFUND_FLAG_THRESHOLD = int(os.environ.get("REFUND_FLAG_THRESHOLD", "3"))

# Cache compartido entre workers: el throttle, el tope global y el lock viven
# acá. En prod (multi-worker) DEBE ser compartido y persistente -> DatabaseCache
# (USE_DB_CACHE=1 + `manage.py createcachetable`). LocMem en prod NO limita:
# cada worker tiene su propio contador y los muros de costo no funcionan.
if os.environ.get("USE_DB_CACHE"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_cache",
        }
    }
else:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise sirve el static del admin sin necesidad de Nginx/CDN. Manifest +
# compresión: requiere `collectstatic` (se corre en el build de la imagen).
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
