"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# DEBUG=1 para desarrollo; en prod se deja sin setear (False).
DEBUG = os.environ.get("DEBUG", "0") == "1"

# SECRET_KEY desde env en prod. El fallback inseguro SOLO existe con DEBUG=1;
# sin DEBUG y sin SECRET_KEY, fail-fast (no arrancar con una key conocida).
SECRET_KEY = os.environ.get("SECRET_KEY") or (
    "django-insecure-$-4_@!44ff*g(ppt70mbj9czrqiy^7i4w$@3m29yr_!%yvf$cp" if DEBUG else ""
)
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY env var es obligatoria cuando DEBUG está apagado")

# Lista separada por comas, p.ej. "api.midominio.com,carta-astral.midominio.com".
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    # En desarrollo el teléfono y la web de la app le pegan por la IP LAN de
    # la Mac (cambia por DHCP); cualquier host es aceptable con DEBUG.
    ALLOWED_HOSTS = ["*"]

# Necesario para el admin (POST de login) sobre HTTPS detrás del proxy de Coolify.
# Lista separada por comas con esquema, p.ej. "https://api.midominio.com".
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Coolify/Traefik terminan TLS y reenvían con X-Forwarded-Proto. Sin esto, Django
# cree que toda request es http y rompe redirects/cookies seguras detrás del proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Hardening sólo en prod (DEBUG off). El redirect HTTP->HTTPS lo hace Coolify/Traefik,
# NO Django (SECURE_SSL_REDIRECT), porque el healthcheck interno pega por HTTP sin el
# header X-Forwarded-Proto y un redirect lo haría fallar.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # conservador: no fuerza HSTS en otros subdominios


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # `wagtail.search` (abajo) define su tabla de índice con `SearchVectorField`
    # y `GinIndex` cuando la base es Postgres (lo decide `modelsearch` mirando
    # `connection.vendor` al importarse). Sin este app, Django no falla al
    # correr sobre SQLite (donde no aplica) pero SÍ falla el `migrate`/
    # `makemigrations` real en producción (Postgres) con
    # `postgres.E005: 'django.contrib.postgres' must be in INSTALLED_APPS`.
    # Verificado en Tarea 9 corriendo el arranque contra Postgres de verdad;
    # el desarrollo local usa SQLite por default y nunca lo disparó.
    "django.contrib.postgres",
    "rest_framework",
    "api",
    # --- CMS de las notas. ---
    # `wagtail.documents` va instalado: sin él, el admin ni siquiera arranca
    # (`wagtailadmin_tags.wagtail_config` reversea su API incondicionalmente,
    # y sin el módulo esa ruta no existe -> 500 en cualquier página del panel,
    # login incluido). Que esté instalado NO significa que se pueda subir nada:
    # `WAGTAILDOCS_EXTENSIONS` (más abajo) bloquea toda subida de documentos,
    # que era XSS almacenado sobre el origen del admin. La lista blanca de
    # extensiones de imagen (Tarea 7) es aparte y también sigue en pie.
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.images",
    "wagtail.documents",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "wagtail.api.v2",
    "modelcluster",
    "taggit",
    "axes",
    "cms",
]

WAGTAIL_SITE_NAME = "ASTRA"
# Wagtail lo exige para armar URLs absolutas en el admin, y la API del CMS la
# usa para armar `full_url` en las imágenes (contrato con la web: usa esa
# clave, no `url`, para las portadas). Mismo patrón que `SECRET_KEY`: default
# a localhost SÓLO en DEBUG; sin la env var en producción, fail-fast en vez de
# arrancar con un default que deja las portadas de todas las notas rotas en
# la web, sin ningún error visible.
WAGTAILADMIN_BASE_URL = os.environ.get("WAGTAILADMIN_BASE_URL") or (
    "http://localhost:8000" if DEBUG else ""
)
if not WAGTAILADMIN_BASE_URL:
    raise ImproperlyConfigured(
        "WAGTAILADMIN_BASE_URL env var es obligatoria cuando DEBUG está apagado: "
        "sin ella, `full_url` en la API de imágenes apunta a localhost y las "
        "portadas de las notas salen rotas en la web."
    )

# Dominio público de la web (Next.js), NO del backend. Este backend es
# headless: `config/urls.py` nunca monta `wagtail.urls`, así que Wagtail no
# tiene ninguna URL propia para una página del CMS. Los enlaces internos del
# cuerpo de una nota (`cms/wagtail_hooks.py`, `NotaLinkHandler`) se resuelven
# contra esta variable, con el esquema de rutas `/notas` que ya define el
# plan del frontend (docs/2026-07-31-spec-cms-wagtail.md). Mismo patrón que
# `WAGTAILADMIN_BASE_URL`: default sólo en DEBUG (puerto de `next dev`),
# fail-fast en producción en vez de publicar enlaces a localhost.
WEB_BASE_URL = os.environ.get("WEB_BASE_URL") or ("http://localhost:3000" if DEBUG else "")
if not WEB_BASE_URL:
    raise ImproperlyConfigured(
        "WEB_BASE_URL env var es obligatoria cuando DEBUG está apagado: sin ella, "
        "los enlaces internos del cuerpo de una nota resolverían contra localhost."
    )

# Un formulario de login expuesto a internet sin límite de intentos no es una
# hipótesis de riesgo: es un problema conocido.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # horas
AXES_LOCKOUT_PARAMETERS = ["ip_address"]
# Sin esto, la IP que axes bloquea es la de Traefik para TODAS las requests, o
# sea que el bloqueo cae sobre todo el mundo a la vez: ver `config/axes_ip.py`.
AXES_CLIENT_IP_CALLABLE = "config.axes_ip.ip_del_cliente"
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # `LANGUAGE_CODE` es global y lo pide el CMS en 'es' (ver más abajo), pero
    # el que decide el idioma de una respuesta de `/api/` es el cliente: sin
    # este middleware, el `detail` de un 429 o un 401 sale en español para la
    # app en inglés y en portugués. Va después de Session y antes de Common,
    # como pide la documentación de Django.
    'django.middleware.locale.LocaleMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

if DEBUG:
    # CORS abierto SOLO en desarrollo, para la build web local de la app.
    MIDDLEWARE.insert(0, 'config.middleware.DevCorsMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
    )
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_AUTHENTICATION_CLASSES": ["api.auth.AccountTokenAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["api.permissions.HasAccount"],
    "DEFAULT_THROTTLE_RATES": {
        "interpretation": os.environ.get("INTERPRETATION_RATE", "20/day"),
        "install": os.environ.get("INSTALL_RATE", "30/day"),
        "auth": os.environ.get("AUTH_RATE", "30/day"),
        "chart": os.environ.get("CHART_RATE", "60/day"),
        # Público y cacheado: el techo es contra el abuso, no contra el uso.
        "sky": os.environ.get("SKY_RATE", "240/hour"),
    },
}

# --- api-interpret (control de costo) ---
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
# Tope global diario de generaciones NUEVAS (cache miss). Las cacheadas no cuentan.
INTERPRETATION_DAILY_CAP = int(os.environ.get("INTERPRETATION_DAILY_CAP", "500"))
# Free-tier: 1 carta gratis por instalación; después, modo pago (IAP, frente con la app).
INSTALL_FREE_CREDITS = int(os.environ.get("INSTALL_FREE_CREDITS", "1"))

# --- SSO / cuentas ---
APPLE_AUD = os.environ.get("APPLE_AUD", "")  # bundle id de la app iOS; vacío => auth Apple 503 (fail-closed)
GOOGLE_AUD = os.environ.get("GOOGLE_AUD", "")  # OAuth client id; vacío => auth Google 503
APPLE_ISS = os.environ.get("APPLE_ISS", "https://appleid.apple.com")
GOOGLE_ISS = os.environ.get("GOOGLE_ISS", "https://accounts.google.com")
APPLE_JWKS_URL = os.environ.get("APPLE_JWKS_URL", "https://appleid.apple.com/auth/keys")
GOOGLE_JWKS_URL = os.environ.get("GOOGLE_JWKS_URL", "https://www.googleapis.com/oauth2/v3/certs")
JWKS_TTL_SECONDS = int(os.environ.get("JWKS_TTL_SECONDS", str(12 * 3600)))
SESSION_TTL_DAYS = int(os.environ.get("SESSION_TTL_DAYS", "90"))

# Credenciales del Apple ID server API (canje de authorization_code + revoke del
# borrado de cuenta, guideline 5.1.1(v)). Fail-OPEN a propósito: sin ellas el
# login y el borrado siguen andando, sólo se saltea el revoke (con log de error).
APPLE_TEAM_ID = os.environ.get("APPLE_TEAM_ID", "")  # Apple Developer → Membership
APPLE_KEY_ID = os.environ.get("APPLE_KEY_ID", "")  # Key ID de la key "Sign in with Apple"
APPLE_PRIVATE_KEY = os.environ.get("APPLE_PRIVATE_KEY", "")  # contenido PEM del .p8

# --- IAP / RevenueCat ---
# Header Authorization que RevenueCat manda en cada webhook (Dashboard → Webhooks).
REVENUECAT_WEBHOOK_AUTH = os.environ.get("REVENUECAT_WEBHOOK_AUTH", "")
# Mapa product_id (App Store / Play) → créditos que otorga. JSON en env.
REVENUECAT_PRODUCT_CREDITS = json.loads(os.environ.get("REVENUECAT_PRODUCT_CREDITS", "{}"))
# Cantidad de reembolsos que marca una cuenta como abuso.
REFUND_FLAG_THRESHOLD = int(os.environ.get("REFUND_FLAG_THRESHOLD", "3"))

# Cache compartido entre workers: el throttle, el tope global y el lock viven
# acá. En prod (multi-worker) DEBE ser compartido y persistente -> DatabaseCache
# (USE_DB_CACHE=1 + `manage.py createcachetable`). LocMem en prod NO limita:
# cada worker tiene su propio contador y los muros de costo no funcionan.
if os.environ.get("USE_DB_CACHE"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_cache",
        }
    }
elif not DEBUG:
    # Fail-fast, no degradación silenciosa: con LocMem cada worker de gunicorn
    # tiene SU PROPIO contador, así que el tope global de gasto, el throttle y
    # el lock de interpretación dejan de limitar sin que nada avise. Es un
    # agujero de costo, y prefiere no arrancar antes que arrancar sin muros.
    raise ImproperlyConfigured(
        "En producción hace falta caché compartida: seteá USE_DB_CACHE=1 "
        "(y corré `manage.py createcachetable`). Con LocMem el cap de costo, "
        "el throttle y el lock de interpretación no limitan nada."
    )
else:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# El contenido del CMS vive en los mismos tres idiomas que la app y la web, y
# éste es el que Wagtail toma como locale por defecto (`Locale.get_default()`).
# OJO: el setting es global, no sólo del CMS — es el idioma de fallback de toda
# respuesta traducible, incluidos los errores de DRF en `/api/`. Que cada
# cliente reciba el suyo lo resuelve `LocaleMiddleware` (ver MIDDLEWARE).
LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

WAGTAIL_I18N_ENABLED = True
WAGTAIL_CONTENT_LANGUAGES = [("es", "Español"), ("en", "English"), ("pt", "Português")]


# Sólo mapas de bits: un SVG es un documento con scripts (RF6).
WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp"]

# `wagtail.documents` va instalado (ver INSTALLED_APPS más arriba: sin él el
# admin no arranca), pero el CMS es para notas de blog —texto e imágenes— y
# no hay ningún caso de uso de documentos. Un `.html` o un `.svg` subidos por
# ese formulario se sirven desde `/media/documents/...`, el mismo origen
# donde vive la sesión del admin: XSS almacenado (verificado, revisión final).
#
# `AbstractDocument.clean()` sólo valida contra `WAGTAILDOCS_EXTENSIONS`
# cuando la lista es truthy (`if allowed_extensions:`): una lista VACÍA no
# activa ninguna validación y dejaría pasar cualquier archivo. Por eso la
# lista lleva una extensión que ningún archivo real puede tener: bloquea
# absolutamente todo, sin el agujero de la lista vacía.
WAGTAILDOCS_EXTENSIONS = ["__ningun-documento-tiene-esta-extension__"]

# La web regenera la nota cuando el CMS avisa. Sin estas dos, no se avisa.
REVALIDATE_URL = os.environ.get("REVALIDATE_URL", "")
REVALIDATE_SECRET = os.environ.get("REVALIDATE_SECRET", "")

# Media (imágenes subidas al CMS)
# https://docs.djangoproject.com/en/6.0/topics/files/

# Fuera de /app, porque el Dockerfile reemplaza ese directorio entero en cada
# deploy (`COPY --from=builder /app /app`). En Coolify este directorio se
# monta como volumen persistente: ver Dockerfile.
#
# En desarrollo `/data/media` no existe y es la raíz del disco: subir una
# portada desde el panel moría con PermissionError al intentar crearlo. Mismo
# patrón que el resto del archivo: default de desarrollo sólo con DEBUG.
MEDIA_ROOT = os.environ.get("MEDIA_ROOT") or (
    str(BASE_DIR / "media") if DEBUG else "/data/media"
)
MEDIA_URL = "/media/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise sirve el static del admin sin necesidad de Nginx/CDN. Manifest +
# compresión: requiere `collectstatic` (se corre en el build de la imagen).
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
